spring:
    datasource:
        driver-class-name:  net.sf.log4jdbc.DriverSpy
        url:                jdbc:log4jdbc:hsqldb:file:${hsqldb.file}
        username:           sa
        password:

mybatis:
    resource:
        config-location:          classpath:/META-INF/mybatis/config.xml
        mapper-locations-pattern: classpath:/jp/co/hotpepper/skeleton/domain/repository/jdbc/*.xml

hsqldb:
    file: app.hsqldb

