CREATE TABLE SALES (
  SLS_ID          VARCHAR(32) NOT NULL,
  SLS_SALES       INTEGER,
  SLS_STR_ID      VARCHAR(32),
  SLS_CST_ID      VARCHAR(32),
  SLS_CREATED     DATE,
  SLS_MODIFIED    DATE,
  PRIMARY KEY(SLS_ID)
);

CREATE TABLE STORE (
  STR_ID          VARCHAR(32) NOT NULL,
  STR_NAME        VARCHAR(256),
  STR_CREATED     DATE,
  STR_MODIFIED    DATE,
  PRIMARY KEY(STR_ID)
);

CREATE TABLE CUSTOMER (
  CST_ID          VARCHAR(32) NOT NULL,
  CST_LASTNAME    VARCHAR(32),
  CST_FIRSTNAME   VARCHAR(32),
  CST_SEX         VARCHAR(1),
  CST_AGE         INTEGER,
  CST_REGION      VARCHAR(32),
  CST_CREATED     DATE,
  CST_MODIFIED    DATE,
  PRIMARY KEY(CST_ID)
);
